#!/bin/bash


YR_RUNTIME_MONITOR_CLASS=""


for f in $(dir ${COMPILER_GENERATED_OUTPUT_FOLDER_FULL_PATH}/*.hpp);
do
    YR_INCLUDE_PATH=$(basename $f)

    RUNTIME_MONITOR_INCLUDE_CODE="${RUNTIME_MONITOR_INCLUDE_CODE}#include \"src/${YR_INCLUDE_PATH}\"\n"

    YR_HEADER_ENDING=".hpp"
    YR_RUNTIME_MONITOR_CLASS="${YR_INCLUDE_PATH%%${YR_HEADER_ENDING}}"
    YR_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE="an_${YR_INCLUDE_PATH%%${YR_HEADER_ENDING}}_instance"

    YR_PRO_FILE_CONTENT_REPLACE="${YR_PRO_FILE_CONTENT_REPLACE}HEADERS += \$\$files(\$\$PWD/src/${YR_INCLUDE_PATH})\n"
    YR_PRO_FILE_CONTENT_REPLACE="${YR_PRO_FILE_CONTENT_REPLACE}SOURCES += \$\$files(\$\$PWD/src/${YR_RUNTIME_MONITOR_CLASS}.cpp)\n\n"

    echo "YR_RUNTIME_MONITOR_CLASS: ${YR_RUNTIME_MONITOR_CLASS}"

    YR_RUNTIME_MONITOR_INSTANTIATION_CODE="${YR_RUNTIME_MONITOR_INSTANTIATION_CODE}${YR_RUNTIME_MONITOR_CLASS} ${YR_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE}(\&logger);\n\t"
    YR_RUNTIME_MONITOR_INSTANTIATION_CODE="${YR_RUNTIME_MONITOR_INSTANTIATION_CODE}new IYRruntimeverificationAdaptor(\&${YR_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE});\n\t"
    YR_RUNTIME_MONITOR_INSTANTIATION_CODE="${YR_RUNTIME_MONITOR_INSTANTIATION_CODE}user_defined_Runtime_Monitors.append(\&${YR_RUNTIME_MONITOR_CLASS_INSTANCE_VARIABLE});\n\n"
done


echo "* include code text:"
printf "${RUNTIME_MONITOR_INCLUDE_CODE}"
printf "${YR_RUNTIME_MONITOR_INSTANTIATION_CODE}"



sed -i \
    "s|#YR-USER-CODE-INCLUDE|${YR_PRO_FILE_CONTENT_REPLACE}|g" \
    "yr-db-runtime-verif.pro"


sed -i \
    "s|\/\/yr-USER-RUNTIME-MONITOR-RELATED-IMPORTS|${RUNTIME_MONITOR_INCLUDE_CODE}|g" \
    "src/yr-db-runtime-verif.cpp"


sed -i \
    "s|\/\/yr-USER-RUNTIME-MONITOR-DECLARATION-INSTANTIATION|${YR_RUNTIME_MONITOR_INSTANTIATION_CODE}|g" \
    "src/yr-db-runtime-verif.cpp"

