#!/bin/bash


for f in $(dir ${COMPILER_GENERATED_OUTPUT_FOLDER_FULL_PATH}/*.hpp);
do
    #YR_RUNTIME_MONITOR_INSTATIATION_CODE="${YR_RUNTIME_MONITOR_INSTATIATION_CODE}\n"
    #YR_RUNTIME_MONITOR_INSTATIATION_CODE="${YR_RUNTIME_MONITOR_INSTATIATION_CODE}\n"

    YR_INCLUDE_PATH=$(basename $f)
    RUNTIME_MONITOR_INCLUDE_CODE="${RUNTIME_MONITOR_INCLUDE_CODE}#include \"src/${YR_INCLUDE_PATH}\"\n"
done

echo "* include code text:"
printf "${RUNTIME_MONITOR_INCLUDE_CODE}"

sed -i \
    "s|yr-USER-RUNTIME-MONITOR-RELATED-IMPORTS|${RUNTIME_MONITOR_INCLUDE_CODE}|g" \
    "src/yr-db-runtime-verif.cpp"

