#############################################################################
# Makefile for building: bin/yr-db-runtime-verif
# Generated by qmake (3.1) (Qt 5.15.2)
# Project:  yr-db-runtime-verif.pro
# Template: app
# Command: /usr/lib/qt5/bin/qmake -o Makefile yr-db-runtime-verif.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_DBUS_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -D_REENTRANT -Wall -Wextra -fPIC $(DEFINES)
INCPATH       = -I. -Imoc -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtWidgets -I/usr/include/x86_64-linux-gnu/qt5/QtGui -I/usr/include/x86_64-linux-gnu/qt5/QtSql -I/usr/include/x86_64-linux-gnu/qt5/QtDBus -I/usr/include/x86_64-linux-gnu/qt5/QtNetwork -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = yr-db-runtime-verif3.0
DISTDIR = /home/yer/yr-db-runtime-verif/obj/yr-db-runtime-verif3.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/home/yer/yr-db-runtime-verif/lib_SD -lyr_sd_runtime_verif /usr/lib/x86_64-linux-gnu/libQt5Widgets.so /usr/lib/x86_64-linux-gnu/libQt5Gui.so /usr/lib/x86_64-linux-gnu/libQt5Sql.so /usr/lib/x86_64-linux-gnu/libQt5DBus.so /usr/lib/x86_64-linux-gnu/libQt5Network.so /usr/lib/x86_64-linux-gnu/libQt5Core.so -lGL -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = obj/

####### Files

SOURCES       = src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp \
		src/widgets/yr-db-runtime-verif-combo-box.cpp \
		src/utils/yr-db-runtime-verif-qmap.cpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.cpp \
		src/windows/yr-db-runtime-verif-windows.cpp \
		src/windows/yr-db-runtime-verif-main-window.cpp \
		src/include/yr-db-runtime-verif-MONITOR.cpp \
		src/yr-db-runtime-verif.cpp \
		src/DBUS/YR_DBUS_COMMON.cpp \
		src/utils/yr-db-runtime-verif-logger.cpp \
		src/utils/yr-db-runtime-verif-sqltable-model.cpp \
		src/utils/yr-db-runtime-verif-utils.cpp \
		src/utils/yr-db-runtime-verif-database-table-column.cpp \
		src/yr-db-runtime-verif-main.cpp \
		src/yr-db-runtime-verif-database.cpp \
		src/yr-db-runtime-verif-config.cpp moc/moc_yr-db-runtime-verif-combo-box.cpp \
		moc/moc_yr-db-runtime-verif-logging-table-widget.cpp \
		moc/moc_yr-db-runtime-verif-windows.cpp \
		moc/moc_yr-db-runtime-verif-main-window.cpp \
		moc/moc_yr-db-runtime-verif-MONITOR.cpp \
		moc/moc_YR_DBUS_COMMON.cpp \
		moc/moc_yr-db-runtime-verif-utils.cpp \
		moc/moc_yr-db-runtime-verif-main.cpp \
		qrc_yr-db-runtime-verif.cpp \
		verif_adaptor.cpp \
		moc/moc_verif_adaptor.cpp
OBJECTS       = obj/yr-db-runtime-verif-LOGGING-INFO.o \
		obj/yr-db-runtime-verif-combo-box.o \
		obj/yr-db-runtime-verif-qmap.o \
		obj/yr-db-runtime-verif-logging-table-widget.o \
		obj/yr-db-runtime-verif-windows.o \
		obj/yr-db-runtime-verif-main-window.o \
		obj/yr-db-runtime-verif-MONITOR.o \
		obj/yr-db-runtime-verif.o \
		obj/YR_DBUS_COMMON.o \
		obj/yr-db-runtime-verif-logger.o \
		obj/yr-db-runtime-verif-sqltable-model.o \
		obj/yr-db-runtime-verif-utils.o \
		obj/yr-db-runtime-verif-database-table-column.o \
		obj/yr-db-runtime-verif-main.o \
		obj/yr-db-runtime-verif-database.o \
		obj/yr-db-runtime-verif-config.o \
		obj/moc_yr-db-runtime-verif-combo-box.o \
		obj/moc_yr-db-runtime-verif-logging-table-widget.o \
		obj/moc_yr-db-runtime-verif-windows.o \
		obj/moc_yr-db-runtime-verif-main-window.o \
		obj/moc_yr-db-runtime-verif-MONITOR.o \
		obj/moc_YR_DBUS_COMMON.o \
		obj/moc_yr-db-runtime-verif-utils.o \
		obj/moc_yr-db-runtime-verif-main.o \
		obj/qrc_yr-db-runtime-verif.o \
		obj/verif_adaptor.o \
		obj/moc_verif_adaptor.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yr-db-runtime-verif.pro src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/include/yr-db-runtime-verif-software-text-configuration.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		src/utils/yr-db-runtime-verif-sqltable-model.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-database-table-column.hpp \
		src/yr-db-runtime-verif-main.hpp \
		src/yr-db-runtime-verif-database.hpp \
		src/yr-db-runtime-verif-config.hpp src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp \
		src/widgets/yr-db-runtime-verif-combo-box.cpp \
		src/utils/yr-db-runtime-verif-qmap.cpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.cpp \
		src/windows/yr-db-runtime-verif-windows.cpp \
		src/windows/yr-db-runtime-verif-main-window.cpp \
		src/include/yr-db-runtime-verif-MONITOR.cpp \
		src/yr-db-runtime-verif.cpp \
		src/DBUS/YR_DBUS_COMMON.cpp \
		src/utils/yr-db-runtime-verif-logger.cpp \
		src/utils/yr-db-runtime-verif-sqltable-model.cpp \
		src/utils/yr-db-runtime-verif-utils.cpp \
		src/utils/yr-db-runtime-verif-database-table-column.cpp \
		src/yr-db-runtime-verif-main.cpp \
		src/yr-db-runtime-verif-database.cpp \
		src/yr-db-runtime-verif-config.cpp
QMAKE_TARGET  = yr-db-runtime-verif
DESTDIR       = bin/
TARGET        = bin/yr-db-runtime-verif


first: all
####### Build rules

bin/yr-db-runtime-verif: ui_yr-db-runtime-verif-main-window.h $(OBJECTS)  
	@test -d bin/ || mkdir -p bin/
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: yr-db-runtime-verif.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		yr-db-runtime-verif.pro \
		yr-db-runtime-verif.qrc
	$(QMAKE) -o Makefile yr-db-runtime-verif.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_charts.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_help.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_x11extras.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xkbcommon_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/moc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resources.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbuscommon.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusinterfaces.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/dbusadaptors.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/uic.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/precompile_header.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
yr-db-runtime-verif.pro:
yr-db-runtime-verif.qrc:
qmake: FORCE
	@$(QMAKE) -o Makefile yr-db-runtime-verif.pro

qmake_all: FORCE


all: Makefile bin/yr-db-runtime-verif

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp src/widgets/yr-db-runtime-verif-combo-box.hpp src/utils/yr-db-runtime-verif-qmap.hpp src/widgets/yr-db-runtime-verif-logging-table-widget.hpp src/windows/yr-db-runtime-verif-windows.hpp src/windows/yr-db-runtime-verif-main-window.hpp src/include/yr-db-runtime-verif-MONITOR.hpp src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp src/utils/yr-db-runtime-verif-definition-format-date-time.hpp src/include/yr-db-runtime-verif-software-text-configuration.hpp src/DBUS/YR_DBUS_COMMON.hpp src/utils/yr-db-runtime-verif-logger.hpp src/utils/yr-db-runtime-verif-sqltable-model.hpp src/utils/yr-db-runtime-verif-utils.hpp src/utils/yr-db-runtime-verif-database-table-column.hpp src/yr-db-runtime-verif-main.hpp src/yr-db-runtime-verif-database.hpp src/yr-db-runtime-verif-config.hpp $(DISTDIR)/
	$(COPY_FILE) --parents yr-db-runtime-verif.qrc $(DISTDIR)/
	$(COPY_FILE) --parents yr.db-runtime.verif.xml $(DISTDIR)/
	$(COPY_FILE) --parents src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp src/widgets/yr-db-runtime-verif-combo-box.cpp src/utils/yr-db-runtime-verif-qmap.cpp src/widgets/yr-db-runtime-verif-logging-table-widget.cpp src/windows/yr-db-runtime-verif-windows.cpp src/windows/yr-db-runtime-verif-main-window.cpp src/include/yr-db-runtime-verif-MONITOR.cpp src/yr-db-runtime-verif.cpp src/DBUS/YR_DBUS_COMMON.cpp src/utils/yr-db-runtime-verif-logger.cpp src/utils/yr-db-runtime-verif-sqltable-model.cpp src/utils/yr-db-runtime-verif-utils.cpp src/utils/yr-db-runtime-verif-database-table-column.cpp src/yr-db-runtime-verif-main.cpp src/yr-db-runtime-verif-database.cpp src/yr-db-runtime-verif-config.cpp $(DISTDIR)/
	$(COPY_FILE) --parents yr.db-runtime.verif.xml $(DISTDIR)/
	$(COPY_FILE) --parents verif_adaptor.h $(DISTDIR)/
	$(COPY_FILE) --parents ui/yr-db-runtime-verif-main-window.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) obj/yr-db-runtime-verif.gch/c obj/yr-db-runtime-verif.gch/c++
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

###### Precompiled headers
obj/yr-db-runtime-verif.gch/c: src/include/yr-db-runtime-verif-precompiled-header.hpp 
	@test -d obj/yr-db-runtime-verif.gch/ || mkdir -p obj/yr-db-runtime-verif.gch/
	$(CC) $(CFLAGS) $(INCPATH) -x c-header -c src/include/yr-db-runtime-verif-precompiled-header.hpp -o obj/yr-db-runtime-verif.gch/c

obj/yr-db-runtime-verif.gch/c++: src/include/yr-db-runtime-verif-precompiled-header.hpp 
	@test -d obj/yr-db-runtime-verif.gch/ || mkdir -p obj/yr-db-runtime-verif.gch/
	$(CXX) $(CXXFLAGS) $(INCPATH) -x c++-header -c src/include/yr-db-runtime-verif-precompiled-header.hpp -o obj/yr-db-runtime-verif.gch/c++

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_moc_predefs_make_all: moc/moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc/moc_predefs.h
moc/moc_predefs.h: /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp \
		obj/yr-db-runtime-verif.gch/c++
	g++ -pipe -g -dM -E -o moc/moc_predefs.h /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc/moc_yr-db-runtime-verif-combo-box.cpp moc/moc_yr-db-runtime-verif-logging-table-widget.cpp moc/moc_yr-db-runtime-verif-windows.cpp moc/moc_yr-db-runtime-verif-main-window.cpp moc/moc_yr-db-runtime-verif-MONITOR.cpp moc/moc_YR_DBUS_COMMON.cpp moc/moc_yr-db-runtime-verif-utils.cpp moc/moc_yr-db-runtime-verif-main.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc/moc_yr-db-runtime-verif-combo-box.cpp moc/moc_yr-db-runtime-verif-logging-table-widget.cpp moc/moc_yr-db-runtime-verif-windows.cpp moc/moc_yr-db-runtime-verif-main-window.cpp moc/moc_yr-db-runtime-verif-MONITOR.cpp moc/moc_YR_DBUS_COMMON.cpp moc/moc_yr-db-runtime-verif-utils.cpp moc/moc_yr-db-runtime-verif-main.cpp
moc/moc_yr-db-runtime-verif-combo-box.cpp: src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/yr-db-runtime-verif-combo-box.hpp -o moc/moc_yr-db-runtime-verif-combo-box.cpp

moc/moc_yr-db-runtime-verif-logging-table-widget.cpp: src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/widgets/yr-db-runtime-verif-logging-table-widget.hpp -o moc/moc_yr-db-runtime-verif-logging-table-widget.cpp

moc/moc_yr-db-runtime-verif-windows.cpp: src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/windows/yr-db-runtime-verif-windows.hpp -o moc/moc_yr-db-runtime-verif-windows.cpp

moc/moc_yr-db-runtime-verif-main-window.cpp: src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/windows/yr-db-runtime-verif-main-window.hpp -o moc/moc_yr-db-runtime-verif-main-window.cpp

moc/moc_yr-db-runtime-verif-MONITOR.cpp: src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/include/yr-db-runtime-verif-MONITOR.hpp -o moc/moc_yr-db-runtime-verif-MONITOR.cpp

moc/moc_YR_DBUS_COMMON.cpp: src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/DBUS/YR_DBUS_COMMON.hpp -o moc/moc_YR_DBUS_COMMON.cpp

moc/moc_yr-db-runtime-verif-utils.cpp: src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/utils/yr-db-runtime-verif-utils.hpp -o moc/moc_yr-db-runtime-verif-utils.cpp

moc/moc_yr-db-runtime-verif-main.cpp: src/yr-db-runtime-verif-main.hpp \
		src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		moc/moc_predefs.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include src/yr-db-runtime-verif-main.hpp -o moc/moc_yr-db-runtime-verif-main.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_rcc_make_all: qrc_yr-db-runtime-verif.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_yr-db-runtime-verif.cpp
qrc_yr-db-runtime-verif.cpp: yr-db-runtime-verif.qrc \
		/usr/lib/qt5/bin/rcc \
		yr-db-runtime-verif-images/LOGO-icon.png \
		yr-db-runtime-verif-images/pdf-print-icon.svg
	/usr/lib/qt5/bin/rcc -name yr-db-runtime-verif yr-db-runtime-verif.qrc -o qrc_yr-db-runtime-verif.cpp

compiler_dbus_adaptor_source_make_all: verif_adaptor.cpp
compiler_dbus_adaptor_source_clean:
	-$(DEL_FILE) verif_adaptor.cpp
verif_adaptor.cpp: yr.db-runtime.verif.xml \
		/usr/lib/qt5/bin/qdbusxml2cpp \
		verif_adaptor.h
	/usr/lib/qt5/bin/qdbusxml2cpp -i verif_adaptor.h -a :verif_adaptor.cpp yr.db-runtime.verif.xml

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_dbus_adaptor_header_make_all: verif_adaptor.h
compiler_dbus_adaptor_header_clean:
	-$(DEL_FILE) verif_adaptor.h
verif_adaptor.h: yr.db-runtime.verif.xml \
		/usr/lib/qt5/bin/qdbusxml2cpp
	/usr/lib/qt5/bin/qdbusxml2cpp -a verif_adaptor.h: yr.db-runtime.verif.xml

compiler_dbus_adaptor_moc_make_all: moc/moc_verif_adaptor.cpp
compiler_dbus_adaptor_moc_clean:
	-$(DEL_FILE) moc/moc_verif_adaptor.cpp
moc/moc_verif_adaptor.cpp: verif_adaptor.h \
		/usr/lib/qt5/bin/moc
	/usr/lib/qt5/bin/moc $(DEFINES) --include /home/yer/yr-db-runtime-verif/moc/moc_predefs.h -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/home/yer/yr-db-runtime-verif -I/usr/include/c++/10 -I/usr/include/x86_64-linux-gnu/c++/10 -I/usr/include/c++/10/backward -I/usr/lib/gcc/x86_64-linux-gnu/10/include -I/usr/local/include -I/usr/include/x86_64-linux-gnu -I/usr/include verif_adaptor.h -o moc/moc_verif_adaptor.cpp

compiler_uic_make_all: ui_yr-db-runtime-verif-main-window.h
compiler_uic_clean:
	-$(DEL_FILE) ui_yr-db-runtime-verif-main-window.h
ui_yr-db-runtime-verif-main-window.h: ui/yr-db-runtime-verif-main-window.ui \
		/usr/lib/qt5/bin/uic \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp
	/usr/lib/qt5/bin/uic ui/yr-db-runtime-verif-main-window.ui -o ui_yr-db-runtime-verif-main-window.h

compiler_no_pch_compiler_make_all:
compiler_no_pch_compiler_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_rcc_clean compiler_dbus_adaptor_source_clean compiler_dbus_adaptor_header_clean compiler_dbus_adaptor_moc_clean compiler_uic_clean 

####### Compile

obj/yr-db-runtime-verif-LOGGING-INFO.o: src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-LOGGING-INFO.o src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp

obj/yr-db-runtime-verif-combo-box.o: src/widgets/yr-db-runtime-verif-combo-box.cpp src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-combo-box.o src/widgets/yr-db-runtime-verif-combo-box.cpp

obj/yr-db-runtime-verif-qmap.o: src/utils/yr-db-runtime-verif-qmap.cpp src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-qmap.o src/utils/yr-db-runtime-verif-qmap.cpp

obj/yr-db-runtime-verif-logging-table-widget.o: src/widgets/yr-db-runtime-verif-logging-table-widget.cpp src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-logging-table-widget.o src/widgets/yr-db-runtime-verif-logging-table-widget.cpp

obj/yr-db-runtime-verif-windows.o: src/windows/yr-db-runtime-verif-windows.cpp src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-windows.o src/windows/yr-db-runtime-verif-windows.cpp

obj/yr-db-runtime-verif-main-window.o: src/windows/yr-db-runtime-verif-main-window.cpp src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-main-window.o src/windows/yr-db-runtime-verif-main-window.cpp

obj/yr-db-runtime-verif-MONITOR.o: src/include/yr-db-runtime-verif-MONITOR.cpp src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-MONITOR.o src/include/yr-db-runtime-verif-MONITOR.cpp

obj/yr-db-runtime-verif.o: src/yr-db-runtime-verif.cpp src/YRruntimeverification_adaptor.h \
		src/yr-db-runtime-verif-main.hpp \
		src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		src/yr-db-runtime-verif-config.hpp \
		src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		src/yr-db-runtime-verif-database.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif.o src/yr-db-runtime-verif.cpp

obj/YR_DBUS_COMMON.o: src/DBUS/YR_DBUS_COMMON.cpp src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		src/yr-db-runtime-verif-config.hpp \
		src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/YR_DBUS_COMMON.o src/DBUS/YR_DBUS_COMMON.cpp

obj/yr-db-runtime-verif-logger.o: src/utils/yr-db-runtime-verif-logger.cpp src/utils/yr-db-runtime-verif-logger.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-logger.o src/utils/yr-db-runtime-verif-logger.cpp

obj/yr-db-runtime-verif-sqltable-model.o: src/utils/yr-db-runtime-verif-sqltable-model.cpp src/utils/yr-db-runtime-verif-sqltable-model.hpp \
		src/utils/yr-db-runtime-verif-database-table-column.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-sqltable-model.o src/utils/yr-db-runtime-verif-sqltable-model.cpp

obj/yr-db-runtime-verif-utils.o: src/utils/yr-db-runtime-verif-utils.cpp src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-utils.o src/utils/yr-db-runtime-verif-utils.cpp

obj/yr-db-runtime-verif-database-table-column.o: src/utils/yr-db-runtime-verif-database-table-column.cpp src/utils/yr-db-runtime-verif-database-table-column.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-database-table-column.o src/utils/yr-db-runtime-verif-database-table-column.cpp

obj/yr-db-runtime-verif-main.o: src/yr-db-runtime-verif-main.cpp src/yr-db-runtime-verif-main.hpp \
		src/include/yr-db-runtime-verif-MONITOR.hpp \
		src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/DBUS/YR_DBUS_COMMON.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EDGE.hpp \
		src/yr_sd_runtime_verif/utils/YR_CPP_UTILS.hpp \
		src/yr_sd_runtime_verif/yr-expressions-conditions/YR_CPP_notinset_inset_TRACE_expression.HPP \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_object.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_EVENT.hpp \
		src/utils/yr-db-runtime-verif-logger.hpp \
		src/yr_sd_runtime_verif/YR_CPP_MONITOR_STATE.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-main.o src/yr-db-runtime-verif-main.cpp

obj/yr-db-runtime-verif-database.o: src/yr-db-runtime-verif-database.cpp src/yr-db-runtime-verif-database.hpp \
		src/yr-db-runtime-verif-config.hpp \
		src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-database.o src/yr-db-runtime-verif-database.cpp

obj/yr-db-runtime-verif-config.o: src/yr-db-runtime-verif-config.cpp src/yr-db-runtime-verif-config.hpp \
		src/windows/yr-db-runtime-verif-windows.hpp \
		src/windows/yr-db-runtime-verif-main-window.hpp \
		ui_yr-db-runtime-verif-main-window.h \
		src/widgets/yr-db-runtime-verif-combo-box.hpp \
		src/utils/yr-db-runtime-verif-utils.hpp \
		src/utils/yr-db-runtime-verif-definition-format-date-time.hpp \
		src/widgets/yr-db-runtime-verif-logging-table-widget.hpp \
		src/utils/yr-db-runtime-verif-qmap.hpp \
		src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp \
		obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/yr-db-runtime-verif-config.o src/yr-db-runtime-verif-config.cpp

obj/moc_yr-db-runtime-verif-combo-box.o: moc/moc_yr-db-runtime-verif-combo-box.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-combo-box.o moc/moc_yr-db-runtime-verif-combo-box.cpp

obj/moc_yr-db-runtime-verif-logging-table-widget.o: moc/moc_yr-db-runtime-verif-logging-table-widget.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-logging-table-widget.o moc/moc_yr-db-runtime-verif-logging-table-widget.cpp

obj/moc_yr-db-runtime-verif-windows.o: moc/moc_yr-db-runtime-verif-windows.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-windows.o moc/moc_yr-db-runtime-verif-windows.cpp

obj/moc_yr-db-runtime-verif-main-window.o: moc/moc_yr-db-runtime-verif-main-window.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-main-window.o moc/moc_yr-db-runtime-verif-main-window.cpp

obj/moc_yr-db-runtime-verif-MONITOR.o: moc/moc_yr-db-runtime-verif-MONITOR.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-MONITOR.o moc/moc_yr-db-runtime-verif-MONITOR.cpp

obj/moc_YR_DBUS_COMMON.o: moc/moc_YR_DBUS_COMMON.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_YR_DBUS_COMMON.o moc/moc_YR_DBUS_COMMON.cpp

obj/moc_yr-db-runtime-verif-utils.o: moc/moc_yr-db-runtime-verif-utils.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-utils.o moc/moc_yr-db-runtime-verif-utils.cpp

obj/moc_yr-db-runtime-verif-main.o: moc/moc_yr-db-runtime-verif-main.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_yr-db-runtime-verif-main.o moc/moc_yr-db-runtime-verif-main.cpp

obj/qrc_yr-db-runtime-verif.o: qrc_yr-db-runtime-verif.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/qrc_yr-db-runtime-verif.o qrc_yr-db-runtime-verif.cpp

obj/verif_adaptor.o: verif_adaptor.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/verif_adaptor.o verif_adaptor.cpp

obj/moc_verif_adaptor.o: moc/moc_verif_adaptor.cpp obj/yr-db-runtime-verif.gch/c++
	$(CXX) -c -include obj/yr-db-runtime-verif $(CXXFLAGS) $(INCPATH) -o obj/moc_verif_adaptor.o moc/moc_verif_adaptor.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/yr-db-runtime-verif || mkdir -p $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/yr-db-runtime-verif
	$(QINSTALL_PROGRAM) bin/$(QMAKE_TARGET) $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/yr-db-runtime-verif/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/yr-db-runtime-verif/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/yr-db-runtime-verif/ 


install_sources: first FORCE
	@test -d $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/. || mkdir -p $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/.
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-LOGGING-INFO.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-LOGGING-INFO.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/widgets/yr-db-runtime-verif-combo-box.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-combo-box.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-qmap.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-qmap.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/widgets/yr-db-runtime-verif-logging-table-widget.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logging-table-widget.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/windows/yr-db-runtime-verif-windows.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-windows.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/windows/yr-db-runtime-verif-main-window.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main-window.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/include/yr-db-runtime-verif-MONITOR.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-MONITOR.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/DBUS/YR_DBUS_COMMON.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./YR_DBUS_COMMON.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-logger.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logger.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-sqltable-model.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-sqltable-model.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-utils.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-utils.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-database-table-column.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database-table-column.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-main.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-database.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-config.cpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-config.cpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-LOGGING-INFO.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-LOGGING-INFO.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/widgets/yr-db-runtime-verif-combo-box.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-combo-box.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-qmap.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-qmap.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/widgets/yr-db-runtime-verif-logging-table-widget.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logging-table-widget.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/windows/yr-db-runtime-verif-windows.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-windows.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/windows/yr-db-runtime-verif-main-window.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main-window.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/include/yr-db-runtime-verif-MONITOR.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-MONITOR.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/include/yr-db-runtime-verif-definition-oo-class-operators.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-definition-oo-class-operators.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-definition-format-date-time.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-definition-format-date-time.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/include/yr-db-runtime-verif-software-text-configuration.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-software-text-configuration.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/DBUS/YR_DBUS_COMMON.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./YR_DBUS_COMMON.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-logger.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logger.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-sqltable-model.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-sqltable-model.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-utils.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-utils.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/utils/yr-db-runtime-verif-database-table-column.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database-table-column.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-main.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-database.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/src/yr-db-runtime-verif-config.hpp $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-config.hpp
	$(QINSTALL) /home/yer/yr-db-runtime-verif/lib.pro $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./lib.pro
	$(QINSTALL) /home/yer/yr-db-runtime-verif/yr-db-runtime-verif.pro $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif.pro

uninstall_sources: FORCE
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./lib.pro
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-config.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database-table-column.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-utils.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-sqltable-model.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logger.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./YR_DBUS_COMMON.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-software-text-configuration.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-definition-format-date-time.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-definition-oo-class-operators.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-MONITOR.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main-window.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-windows.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logging-table-widget.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-qmap.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-combo-box.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-LOGGING-INFO.hpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-config.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-database-table-column.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-utils.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-sqltable-model.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logger.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./YR_DBUS_COMMON.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-MONITOR.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-main-window.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-windows.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-logging-table-widget.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-qmap.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-combo-box.cpp
	-$(DEL_FILE) -r $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./yr-db-runtime-verif-LOGGING-INFO.cpp
	-$(DEL_DIR) $(INSTALL_ROOT)/home/yer/yr-db-runtime-verif/./ 


install: install_target install_sources  FORCE

uninstall: uninstall_target uninstall_sources  FORCE

FORCE:

