#!/bin/bash

ln -s /lib/systemd/system/yr-db-runtime-verif.service /etc/systemd/system/yr-db-runtime-verif.service

systemctl daemon-reload &

systemctl enable yr-db-runtime-verif.service &

systemctl start yr-db-runtime-verif.service &

chmod +x /etc/init.d/yr-db-runtime-verif.sh 

update-rc.d yr-db-runtime-verif.sh defaults

/etc/init.d/yr-db-runtime-verif.sh start & 
