export YR_SD_MEALY_MACHINE_COMPILER_FULL_PATH=$HOME/yr_sd_runtime_verif_lang/yr_sd_runtime_verif_lang_comp
export YR_SD_MEALY_MACHINE_SPEC_FOLDER_FULL_PATH=$HOME/yr-db-runtime-verif/projet-de-tests-yr-nissi/sd-mealy-machine-specs
